
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/nxcar-in
            git pull origin main
            cd client && npm install && npm run build && cd ..
            ./scripts/run-migrations.sh
            pm2 restart myapp-nxcar-in
            pm2 save